FROM node:20-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY index.js ./

RUN mkdir -p uploads/hdf5

EXPOSE 3000

CMD ["node", "index.js"]
